DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

api/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: urls.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午11:15
     History:   
"""

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       # 资产管理
                       url(r'^project/$', 'assets.api.api.type_list'),
                       url(r'^project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),
                       url(r'^user/.*$', 'assets.api.api.user_select'),

                       # 装机操作
                       url(r'^sn/.*$', 'assets.api.api.Sn_number'),
                       url(r'^cmdb/.*$', 'assets.api.api.CmdbUpdate'),

                       # nagios监控接口

                       url(r'^audit/list/.*$', 'audit.views.audit_list'),

                       url(r'^audit/$', 'audit.views.audit_save'),
                       # url(r'^create', 'assets.api.api.saltstack_create_config'),

                       # 安装完成上报接口
                       url(r'^system_install/$', 'assets.value_class.index.install_ok'),
                       url(r'^alert/$', 'malfunction.views.FaultApi'),
                       url(r'^monitor/http', 'monitor.views.HttpMonitorApi'),
                       url(r'^monitor/log', 'api.monitor_api.HttpMonitorLog'),
                       url(r'^xls/', 'api.cmdb_excel.xls_select'),
                       url(r'^cdn/', 'api.cmdb_excel.xls_cdn'),

                       )

assets/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 
#      History:
# =============================================================================

from django.conf.urls import patterns, include, url
from assets import views, service_views, salt_cdn_cmdb

urlpatterns = patterns('',
                       # 资产管理
                       url(r'^server/select_business/$', 'assets.value_class.index.select_business',
                           name="select_business"),
                       url(r'^server/update_cabinet/$', 'assets.value_class.index.update_cabinet',
                           name="update_cabinet"),
                       url(r'^server/update_system/$', 'assets.value_class.index.update_system',
                           name="update_system"),
                       url(r'^server/host_without_business/', 'assets.value_class.index.host_without_business'),
                       url(r'^server/auth_without_business/$',
                           'assets.value_class.index.auth_host_without_business'),
                       url(r'^server/restart/(?P<uuid>[^/]+)/', 'assets.value_class.index.restart_node', name="install_system"),
                       url(r'^host_detail/$', "assets.views.host_detail", name="host_detail"),
                       url(r'^host_list/$', "assets.views.host_list"),
                       url(r'^host_add/$', "assets.views.host_add"),
                       url(r'^host_edit/$', "assets.views.host_edit", name="host_edit"),
                       url(r'^host_edit_batch/$', "assets.views.host_edit_batch"),
                       url(r'^host_update/$', "assets.views.host_update"),
                       url(r'^host_del/$', "assets.views.host_del", name='host_del'),
                       url(r'^host_del_batch/$', "assets.views.host_del_batch"),
                       url(r'^host_add_batch/$', "assets.views.host_add_batch"),
                       url(r'^change_info_ajax/$', "assets.views.host_search"),
                       url(r'^host_search/$', "assets.views.host_search"),
                       url(r'^idc_add/$', "assets.views.idc_add"),
                       url(r'^idc_list/$', "assets.views.idc_list"),
                       url(r'^idc_edit/$', "assets.views.idc_edit"),
                       url(r'^idc_del/$', "assets.views.idc_del"),
                       url(r'^zabbix/$', "assets.views.zabbix_info"),
                       url(r'^zabbix_host/$', "assets.views.zabbix_host"),
                       url(r'^ip_list/$', "assets.views.ip_list"),
                       url(r'^ip_list_ajax/$', "assets.views.ip_list_ajax"),
                       url(r'^ip_list_info/$', "assets.views.ip_list_info"),
                       url(r'^test/$', "assets.salt_cdn_cmdb.test"),

                       # 机房操作
                       url(r'server/room/add/', 'assets.value_class.Engine_room.add_room'),
                       url(r'server/room/list/', 'assets.value_class.Engine_room.room_list'),
                       url(r'server/room/edit/(?P<id>\d+)/$', 'assets.value_class.Engine_room.room_edit'),
                       url(r'server/room/delete/(?P<id>\d+)/$', 'assets.value_class.Engine_room.room_delete'),

                       # 服务操作
                       url(r'service_add/$', "assets.service_views.service_add"),
                       url(r'service_edit/$', "assets.service_views.service_edit"),
                       url(r'service_list/$', "assets.service_views.service_list"),
                       url(r'service_del/$', "assets.service_views.service_del"),

                       # 项目管理
                       url(r'^server/user_auth/$', 'assets.value_class.business.server_type_auth',
                           name="user_idc_auth_server"),
                       url(r'^server/type/item_ajax/$', 'assets.value_class.business.business_item_ajax',
                           name="business_item_ajax"),
                       url(r'^server/type/(?P<uuid>[^/]+)/host_list/$',
                           'assets.value_class.business.business_host_list', name="business_host_list"),
                       url(r'^server/type/add/', 'assets.value_class.business.server_type_add'),
                       url(r'^server/type/list/', 'assets.value_class.business.auth_server_type_list', name='project_list'),

                       url(r'^server/type/edit/(?P<uuid>[^/]+)/$',
                           'assets.value_class.business.auth_server_type_edit', name="project_edit_ajax"),
                       url(r'^server/type/del/(?P<uuid>[^/]+)/$',
                           'assets.value_class.business.auth_server_type_del'),

                       url(r'^server/type/doc/(?P<uuid>[^/]+)/$', 'assets.value_class.business.project_doc',
                           name="project_doc"),
                       url(r'^server/type/edit_doc/(?P<uuid>[^/]+)/$',
                           'assets.value_class.business.project_doc_edit', name="project_doc_edit"),

                       url(r'^server/server_type/$', 'assets.value_class.business.server_type_item'),

                       # 项目用户
                       url(r'^server/type/edit/(?P<uuid>[^/]+)/user/$',
                           'assets.value_class.business.auth_server_type_user_select', name="business_user_edit"),
                       url(r'^server/type/edit/(?P<uuid>[^/]+)/user/add/$',
                           'assets.value_class.business.auth_server_type_user_add', name="business_user_add"),
                       url(r'^server/type/edit/(?P<id>\d+)/user/edit/$',
                           'assets.value_class.business.auth_server_type_user_edit', name="business_useredit"),
                       url(r'^server/type/edit/(?P<id>\d+)/user/delete/$',
                           'assets.value_class.business.auth_server_type_user_delete'),

                       # 操作日志
                       url(r'^server/batch/', 'assets.value_class.index.Index_add_batch'),

                       url(r'^server/bat/.*$', 'assets.value_class.index.batadd'),
                       url(r'^server/order_by/.*$', 'assets.value_class.index.server_order_by'),
                       url(r'^search/.*$', 'assets.value_class.index.Node_search', name="search"),
                       url(r'^cabinet/.*$', 'assets.value_class.index.search_cabinet', name="cabinet"),
                       url(r'^default/$', 'assets.value_class.index.select_default', name="default"),
                       url(r'^select', 'assets.value_class.index.Node_select'),
                       url(r'^filter/', 'assets.value_class.index.node_filter'),
                       # url(r'test_update/.*$', 'assets.value_class.index.node_update'),
                       # 添加业务线
                       url(r'^product/add/$', 'assets.value_class.product_line.product_add', name="product_add"),
                       url(r'^product/edit/(?P<uuid>[^/]+)/$', 'assets.value_class.product_line.product_edit',
                           name="product_edit"),
                       url(r'^product/list/$', 'assets.value_class.product_line.product_list', name="product_list"),

                       url(r'^server/install/$', 'assets.value_class.index.txt_update'),

                       # ztree
                       url(r'^ztree/project/$', 'assets.ztree.api.ztree_project'),
                       url(r'^ztree/business/$', 'assets.ztree.api.ztree_business'),
                       url(r'^ztree/cdn/$', 'assets.ztree.api.CdnCache'),
                       url(r'^ztree/idc/$', 'assets.ztree.api.CdnIdc'),

                       #   服务查询
                       url(r'^ztree/service/(?P<uuid>\w+)/$', 'assets.ztree.service.ServiceStatus',
                           name="service_status"),
                       url(r'^ztree/service/$', 'assets.ztree.service.ztree_service'),
                       url(r'^ztree/$', 'assets.ztree.api.ZtreeIndex'),
                       url(r'^markdown/select/(?P<uuid>[^/]+)/', "assets.views.MarkDown_content", name="MarkDown_content"),
                       url(r'^markdown/edit/(?P<uuid>[^/]+)/$', "assets.views.MarkDown_edit", name="MarkDown_edit"),
                       url(r'^markdown/', "assets.views.MarkDown_edit", name="MarkDown_edit"),
                       url(r'^server/$', 'assets.views.host_list'),
                       # url(r'$/', "assets.views.host_list"),

                       )

mysite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 2013-02-20 14:52:11
#      History:
# =============================================================================

from django.conf.urls import patterns, include, url
from mysite.settings import MEDIA_ROOT
from django.contrib import admin
from settings import BASE_DIR

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "%s/upload" % BASE_DIR}),

                       url(r'accounts/', include("accounts.urls")),
                       # url(r'^$', 'salt_ui.auto.auto_index_class.auto_index'),
                       url(r'^$', 'salt_ui.views.index.salt_index_new'),
                       url(r'^login/$', 'salt_ui.views.index.auth_login'),
                       url(r'^test/$', 'salt_ui.views.index.test'),
                       # 日志
                       url(r'^logs/salt/', 'salt_ui.views.api_log_class.salt_data_log'),
                       url(r'^logs/host/', "audit.views.audit_list"),

                       # 搜索
                       # url(r'^search/$', 'assets.views.search'),
                       # salt_ui
                       url(r'salt/', include("salt_ui.urls")),
                       # 资产管理
                       url(r'assets/', include("assets.urls")),
                       # url(r'',include(salt_ui.urls)),
                       # 运维自动化
                       url(r'auto/', include("salt_ui.auto.urls")),
                       # 资产api
                       url(r'api/', include("api.urls")),
                       url(r'conf/', include("config.urls")),

                       # 审计模块
                       url(r'^audit/', include("audit.urls")),

                       # admin
                       url(r'^admin/', include(admin.site.urls)),

                       # swan发布接口
                       url(r'swan/', include("swan.urls")),

                       # 故障管理
                       url(r'^incident/', include("malfunction.urls")),

                       # 监控
                       url(r'^monitor/', include("monitor.urls")),

                       # message
                       url(r'^message/', include("message.urls")),

                       # 权限组
                       url(r'^auth/', include("cmdb_auth.urls")),

                       url(r'^ops/doc/$', 'salt_ui.views.index.OpsDoc'),
                       url(r'^api/project/$', 'assets.api.api.type_list'),
                       url(r'^api/project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),

                       url(r'^ueditor/', include('DjangoUeditor.urls')),


                       # url(r'^summernote/', include('django_summernote.urls')),
                       #
                       )

audit/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#      History:
# =============================================================================

import json, time, urllib
from django.shortcuts import render_to_response, get_object_or_404
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from audit.models import ssh_audit
from django.views.decorators.csrf import csrf_exempt
# 登录
from cmdb_auth.no_auth import check_auth

import requests, re


@csrf_exempt
def audit_save(request):
    """
    用户操作记录入库
    user_name = models.CharField(max_length=20, verbose_name=u'操作用户')
    bash_shell = models.TextField(verbose_name=u'命令')
    audit_data_time = models.DateTimeField(verbose_name=u'操作时间')
    server_ip = models.IPAddressField(verbose_name=u'服务器ip')
    """
    if request.method == 'POST':
        user_name = request.POST.get("user_name")
        bash_shell = request.POST.get("bash_shell")
        audit_data_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))
        server_ip = request.POST.get("server_ip")
        # data = ssh_audit_log(user_name, bash_shell, audit_data_time, server_ip)
        ssh_audit_data = ssh_audit(user_name=user_name, bash_shell=bash_shell, audit_data_time=audit_data_time,
                                   server_ip=server_ip)
        s = ssh_audit_data.save()
    return HttpResponse(json.dumps({"status": 200, "result": u"已入库"}, ensure_ascii=False, indent=4, ))


@csrf_exempt
def audit_list(request):
    """
    用户审计记录
    :param requests:
    :return:
    """
    status = check_auth(request, "server_audit")
    if not status:
        return render_to_response('default/error_auth.html', locals(), context_instance=RequestContext(request))

    audit_data = ssh_audit.objects.all().order_by("-audit_data_time")
    return render_to_response('audit/list.html', locals(), context_instance=RequestContext(request))


@csrf_exempt
def audit_select(request):
    """
    查询服务器操作记录
    """
    # ip = "192.168.8.225"
    if request.method == 'POST':
        ip = request.POST.get("ip")
        try:
            audit_page = int(request.POST.get("num"))
        except:
            audit_page = 0
        if audit_page > 0:
            num = audit_page
            audit_data = ssh_audit.objects.filter(server_ip=ip).order_by("-audit_data_time")[:num]
        else:
            audit_data = ssh_audit.objects.filter(server_ip=ip).order_by("-audit_data_time")

        data = []
        for i in audit_data:
            # content[ip]
            data.append({"bash_shell": "%s  %s     %s" % (i.user_name, i.audit_data_time, i.bash_shell)})
        # print data

        return HttpResponse(json.dumps({"status": 200, "result": data}, ensure_ascii=False, indent=4), content_type="application/json")

    return HttpResponse(json.dumps({"status": 403, "result": "error"}, ensure_ascii=False, indent=4), content_type="application/json")

templates/assets/auth_type.html
{% block content %}
        <div class="form-group">
            <label class="control-label col-sm-2 col-lg-2 " for="id_user_name">选择需要授权主机</label>
            <div class=" col-sm-5 col-lg-5 ">
                <table class="table table-condensed table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                <input type="checkbox" value="" id="select_all" /> 全选
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tab-add">
                        {% for i in server_list %}
                            <tr>
                            {% if i.status == 1 %}
                                {% if i.uuid not in ip_list %}
                                    <td> <input type="checkbox" value="{{ i.uuid }}" name="node" /> {{ i.eth1 }}</td>
                                {% endif %}
                            {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class=" col-sm-5 col-lg-5 ">
                <table class="table table-condensed table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                已分配权限主机
                            </th>
                            <th>权限</th>
                            <th>
                                删除
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data %}
                            {% if i.node.status == 1 %}
                                <tr id="{{ i.id }}">
                                        <td>{{ i.node.eth1 }}</td>
                                        <td> <a class="btn btn-xs btn-success" href="{{ i.id }}">{% if i.auth %}管理员{% else %}普通用户{% endif %}</a></td>
                                        <td> <a class="save_delete" id="{{ i.id }}" value="{{ i.node.uuid }}" name="{{ i.node.eth1 }}" href="/accounts/server/auth/delete/?uuid={{ i.node.uuid }}&auth_id={{ user_data.uuid }}" onclick="return false">删除</a></td>
                                </tr>
                            {% endif %}
                        {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>

<script>
    $('.save_delete').unbind('click').bind('click',function(){
      $("tr[id='"+$(this).attr("id")+"']").remove();
      var node_name_data= $(this).attr("name");
      var node_name_uuid= $(this).attr("value");
      $.ajax({
         type: "GET",
         node_name_data: $(this).attr("name"),
         url: $(this).attr("href") }).done(function( data ) {
          $("#tab-add").append("<tr>"
                               +"<td>"+"<input type=\"checkbox\" value=" + node_name_uuid + " name=\"node_name\">" + node_name_data + "</td>"
                           +"</tr>");
         return false;
      });
    });
    // 请求保存
     $('.edit-save').unbind('click').bind('click',function(){
          $.ajax({
              type: "POST",
              url: $(this).attr("href"),                  // 提交的页面
              data: $('#form_data').serialize(), // 从表单中获取数据
              dataType:'text',
              success: function(msg){
                  // alert(msg);
                  $("#edit_result").html(msg);
              }
          });return false;
         });
    $(document).on("click","#select_all",function(e){
           var selected = $("#select_all").prop("checked");
           if(selected){
             $("input[name='node']").prop('checked',true);
           }else{
             $("input[name='node']").prop("checked",false);
           }
         });
</script>

{% endblock content %}





templates/assets/bottom.html


</body>
</html>

templates/assets/business_item_widget.html
{#<h1>{{ item }}</h1>#}
<p>主要联系人: {{ item.project_contact }} 第二联系人: {{ item.project_contact_backup }}</p>
<ul class="nav nav-pills">
    <li ><button href="{% url 'business_host_list' item.id %}" class="btn btn-primary btn-action click" >项目环境</button></li>
    <li>  <button href="{% url 'business_user_edit' item.id %}" class="btn btn-primary btn-action click" >权限管理</button> </li>
    <li ><button href="{% url 'project_doc' item.id %}" class="btn btn-primary btn-action click">维护文档</button></li>
    <li ><button href="{% url 'project_edit_ajax' item.id %}" class="btn btn-primary btn-action click">项目修改</button></li>
</ul>
<p></p>
<div id="status">

</div>

<script>
 $(function(){
    $('.click').unbind('click').bind('click',function(){
      var url= $(this).attr("href");
         $.ajax({
             type: "GET",
             url: url }).done(function( data ) {
             $("#status").html(data);
         });
         $(".nav-pills >li > button").attr("class", "btn btn-primary btn-action click");
         $(this).attr("class", "btn btn-success btn-action click");
    });

     $('.click-save').unbind('click').bind('click',function(){
         var url= $(this).attr("href");
         $.ajax({
             type: "POST",
             url: $(this).attr("href"),                  // 提交的页面
             data: $('#form_data').serialize(), // 从表单中获取数据
             dataType:'text',
             success: function(msg){
                 $("#data_ok").html(msg)                    // 设置表单提交完成使用方法
             }
         });
      });

 })

</script>





templates/assets/idc_add.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>添加IDC机房 | Add IDC.</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-10">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> 填写机房详细信息 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user"></ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <form class="form-horizontal"  method="post" role="form" >
                        {% csrf_token %}
                        {% if emg %}
                            <div class="alert alert-warning text-center">{{ emg }}</div>
                        {% endif %}
                        {% if smg %}
                            <div class="alert alert-success text-center">{{ smg }}</div>
                        {% endif %}
                        {{ uf |bootstrap_horizontal }}

                        <div class="form-group">
                           <div class="col-sm-4 col-sm-offset-5">
                               <button class="btn btn-white" type="submit"> 重置 </button>
                               <button class="btn btn-primary" type="submit"> 提交 </button>
                           </div>
                       </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}






templates/assets/idc_edit.html
{% extends 'assets/base.html' %}
{% load bootstrap %}
{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>编辑IDC机房 | Edit IDC.</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-10">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> 填写机房详细信息 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user"></ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <form class="form-horizontal"  method="post" role="form" >
                        {% csrf_token %}
                        {{ uf |bootstrap_horizontal }}

                        <div class="form-group">
                           <div class="col-sm-4 col-sm-offset-5">
                               <button class="btn btn-white" type="submit"> 重置 </button>
                               <button class="btn btn-primary" type="submit"> 提交 </button>
                           </div>
                       </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}






templates/assets/server_desc.html
{% include 'op_header.html' %}
<script type="text/javascript" src="/static/js/highslide/highslide-with-html.js"></script>
<link rel="stylesheet" type="text/css" href="/static/js/highslide/highslide.css" />
<!-- 弹出浮动层 -->
<style>
.voilet_search{float:right;padding-right:100px;}
</style>
<div class="voilet">
    <div class="voilet_search">
        <form class="form-search" method="get" action="/search/server/">
            <input class="input-medium search-query" type="text" name=search />
            <button class="btn" contenteditable="true" id = ip type="submit">查找</button>
        </form>
    </div>
</div>
			<table class="table"> <!-- <table class="table table-condensed"> -->
				<thead>
					<tr>
						<th>
							资产编号
						</th>
						<th>
							远控卡IP
						</th>
						<th>
							网卡1
						</th>
                        <th>
							网卡2
						</th>
                        <th>
							所属机房
						</th>
						<th>
							机柜位置
						</th>
						<th>
							cpu/内存/硬盘
						</th>
						<th>
							服务器型号
						</th>
                        <th>
							快速服务代码
						</th>
                        <th>
							修改
						</th>
					</tr>
				</thead>
				<tbody>
                {% for list in emps %}
					<tr>
						<td>
							<a href="/server/list_id/{{ list.id }}">{{ list.Server_Asset_number }}</a>
						</td>
						<td>
							{{ list.Server_Remote_control_card }}
						</td>
						<td>
							{{ list.Server_eth1 }}
						</td>
                        <td>
							{{ list.Server_eth2 }}
						</td>
                        <td>
							<a href="/server/room_id/{{ list.Server_engine_room_id }}">{{ list.Server_engine_room }}</a><!-- 所属机房-->
						</td>
						<td>
							<a href="/server/Location_id/{{ list.Server_number_Location_id }}">{{ list.Server_number_Location }} 柜 {{ list.Server_cabinet_id }}</a>
						</td>
						<td>
							{{ list.Server_Memory }}
						</td>
						<td>
							{{ list.Server_Model }}
						</td>
                        <td>
                            {{ list.Server_number_code }}
                        </td>
                        <td>
							<a href="/server/edit_id/{{ list.id }}" target=_blank onclick="return hs.htmlExpand(this, { objectType: 'iframe',width:1200,height:1200,} )" id="goto" >修改</a>
						</td>
                    </tr>
                {% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% include 'op_bottom.html' %}

<script type="text/javascript">
hs.graphicsDir = '/static/js/highslide/graphics/';
hs.outlineType = 'rounded-white';
hs.wrapperClassName = 'draggable-header';

</script>

templates/assets/server_over.html
{% include 'op_header.html' %}


<div class="hero-unit">
    <h3>
        <li style="color:#FD0301">服务器详细配置：</li>
    </h3></br>
    <table class="table" contenteditable="true">
        <thead>
            <tr>
                <th>资产编号</th>
                <th>网卡1</th>
                <th>网卡2</th>
                <th>远控卡</th>
                <th>所属机房</th>
                <td>内存硬盘</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ id.Server_Asset_number }}</td>
                <td>{{ id.Server_eth1 }}</td>
                <td>{{ id.Server_eth2 }}</td>
                <td>{{ id.Server_Remote_control_card }}</td>
                <td>{{ id.Server_engine_room }}</td>
                <td>{{ id.Server_Memory }}</td>
            </tr>
        </tbody>
    </table>
    <p>
        业务：{% for i in  Business_over %} {{ i }}  {% endfor %}
    </p>
    <p>
        服务器型号：{{ id.Server_Model }}
    </p>
    <p>
        服务器编码：{{ id.Server_number }}
    </p>
     <p>
        快速服务代码：{{ id.Server_number_code }}
    </p>
    <p>
        机柜：{{ id.Server_number_Location }} －{{ id.Server_cabinet_id }}
    </p>
    <p>
        cacti：{{ id.Server_cacti }}
    </p>
     <p>
        备注：{{ id.Server_number_Remark|safe }}
    </p>
</div>

{% include 'op_bottom.html' %}

templates/assets/server_search.html
{% include 'op_header.html' %}
{% id %}

{% include 'op_bottom.html' %}

templates/assets/upload.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ title }}</title>
    <meta name="keywords" content="{{ keywords }}"/>
    <meta name="description" content="{{ description }}"/>
</head>
<body>

</body>
</html>