DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

api/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: urls.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午11:15
     History:   
"""

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       # 资产管理
                       url(r'^project/$', 'assets.api.api.type_list'),
                       url(r'^project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),
                       url(r'^user/.*$', 'assets.api.api.user_select'),

                       # 装机操作
                       url(r'^sn/.*$', 'assets.api.api.Sn_number'),
                       url(r'^cmdb/.*$', 'assets.api.api.CmdbUpdate'),

                       # nagios监控接口

                       url(r'^audit/list/.*$', 'audit.views.audit_list'),

                       url(r'^audit/$', 'audit.views.audit_save'),
                       # url(r'^create', 'assets.api.api.saltstack_create_config'),

                       # 安装完成上报接口
                       url(r'^system_install/$', 'assets.value_class.index.install_ok'),
                       url(r'^alert/$', 'malfunction.views.FaultApi'),
                       url(r'^monitor/http', 'monitor.views.HttpMonitorApi'),
                       url(r'^monitor/log', 'api.monitor_api.HttpMonitorLog'),
                       url(r'^xls/', 'api.cmdb_excel.xls_select'),
                       url(r'^cdn/', 'api.cmdb_excel.xls_cdn'),

                       )

monitor/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName: urls.py
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 2014-02-27
#      History: 
# =============================================================================

from django.conf.urls import patterns, url
from config.operation import *

urlpatterns = patterns('',
                       url(r'^$', "config.add_config_class.salt_conf_index"),
                       url(r'^http/add/$', "monitor.views.HttpMonitor", name="HttpMonitor"),
                       url(r'^http/edit/(?P<uuid>[^/]+)/', "monitor.views.HttpMonitorEdit", name="HttpMonitorEdit"),
                       url(r'^http/status/(?P<uuid>[^/]+)/$', "monitor.views.HttpMonitorstatus", name="HttpMonitorstatus"),
                       url(r'^http/del/(?P<uuid>[^/]+)/$', "monitor.views.HttpMonitorDel", name="HttpMonitorDel"),
                       url(r'^http/detail/(?P<uuid>[^/]+)/', "monitor.views.HttpMonitorPage", name="HttpMonitorPage"),
                       url(r'^http/list/$', "monitor.views.HttpMonitorlist", name="httpmonitorlist"),
                       )

mysite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 2013-02-20 14:52:11
#      History:
# =============================================================================

from django.conf.urls import patterns, include, url
from mysite.settings import MEDIA_ROOT
from django.contrib import admin
from settings import BASE_DIR

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "%s/upload" % BASE_DIR}),

                       url(r'accounts/', include("accounts.urls")),
                       # url(r'^$', 'salt_ui.auto.auto_index_class.auto_index'),
                       url(r'^$', 'salt_ui.views.index.salt_index_new'),
                       url(r'^login/$', 'salt_ui.views.index.auth_login'),
                       url(r'^test/$', 'salt_ui.views.index.test'),
                       # 日志
                       url(r'^logs/salt/', 'salt_ui.views.api_log_class.salt_data_log'),
                       url(r'^logs/host/', "audit.views.audit_list"),

                       # 搜索
                       # url(r'^search/$', 'assets.views.search'),
                       # salt_ui
                       url(r'salt/', include("salt_ui.urls")),
                       # 资产管理
                       url(r'assets/', include("assets.urls")),
                       # url(r'',include(salt_ui.urls)),
                       # 运维自动化
                       url(r'auto/', include("salt_ui.auto.urls")),
                       # 资产api
                       url(r'api/', include("api.urls")),
                       url(r'conf/', include("config.urls")),

                       # 审计模块
                       url(r'^audit/', include("audit.urls")),

                       # admin
                       url(r'^admin/', include(admin.site.urls)),

                       # swan发布接口
                       url(r'swan/', include("swan.urls")),

                       # 故障管理
                       url(r'^incident/', include("malfunction.urls")),

                       # 监控
                       url(r'^monitor/', include("monitor.urls")),

                       # message
                       url(r'^message/', include("message.urls")),

                       # 权限组
                       url(r'^auth/', include("cmdb_auth.urls")),

                       url(r'^ops/doc/$', 'salt_ui.views.index.OpsDoc'),
                       url(r'^api/project/$', 'assets.api.api.type_list'),
                       url(r'^api/project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),

                       url(r'^ueditor/', include('DjangoUeditor.urls')),


                       # url(r'^summernote/', include('django_summernote.urls')),
                       #
                       )

monitor/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from users.models import CustomUser
import time
from uuidfield import UUIDField


class MonitorHttp(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    title = models.CharField(max_length=120, verbose_name=u"监控名称")
    url = models.TextField(verbose_name=u'监控url', help_text=u'同一组服务器多个url监控换行即可')
    monitor_type = models.BooleanField(default=True, verbose_name=u'请求方式')
    monitor_ip = models.TextField(verbose_name=u'ip列表')
    mail_status = models.BooleanField(verbose_name=u"是否邮件报警", default=True)
    mail = models.TextField(verbose_name=u'邮件联系人', help_text=u'多个邮件联系人换行即可')
    weixin_status = models.BooleanField(verbose_name=u'是否微信报警', default=True)
    weixin = models.TextField(verbose_name=u'微信联系人', help_text=u'多个联系人换行即可')
    payload = models.TextField(verbose_name=u'post数据', null=True, blank=True, help_text=u'POST提交数据,需json格式')
    status = models.BooleanField(verbose_name=u'状态', default=True)
    result_code = models.BooleanField(verbose_name=u'header/code', default=True,
                                      help_text=u'默认监控http status,如果选择为返回值,则监控返回数据retCode是否为200')
    createtime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u"http监控"
        verbose_name_plural = verbose_name


class MonitorHttpLog(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    monitorId = models.CharField(max_length=120, verbose_name=u"监控ID")
    monitor_title = models.CharField(max_length=120, verbose_name=u"监控名称")
    content = models.TextField(verbose_name=u"日志内容", null=True, blank=True)
    code = models.IntegerField(verbose_name=u'状态码')
    job_id = models.CharField(max_length=32, verbose_name=u'任务id')
    status = models.BooleanField(verbose_name=u'状态', default=True)
    createtime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.monitor_title

    class Meta:
        verbose_name = u"http监控日志"
        verbose_name_plural = verbose_name


class MonitorMySql(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    name = models.CharField(max_length=120, verbose_name=u"监控名称")
    monitor_ip = models.TextField(verbose_name=u'ip列表')
    monitor_user = models.CharField(verbose_name=u'用户名', max_length=32, help_text=u'监控帐号')
    monitor_pass = models.CharField(verbose_name=u'用户名', max_length=128, help_text=u'监控密码')
    monitor_port = models.IntegerField(verbose_name=u'端口', help_text=u'mysql端口')
    mail = models.TextField(verbose_name=u'邮件', help_text=u'多个邮件联系人换行即可')
    weixin = models.TextField(verbose_name=u'微信', help_text=u'多个联系人换行即可')
    slave = models.BooleanField(verbose_name=u'主从', default=True)
    status = models.BooleanField(verbose_name=u'状态', default=True)
    createtime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"mysql监控"
        verbose_name_plural = verbose_name

monitor/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: forms.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午3:46
     History:   
"""

from models import MonitorHttp, MonitorHttpLog
from django import forms

BOOL_CHOICES = ((True, 'GET'), (False, 'POST'))
BOOL_RESULT = ((True, 'http状态'), (False, '返回值'))
BOOL_STATUS = ((True, '是'), (False, '否'))


class MonitorHttpForm(forms.ModelForm):
    monitor_type = forms.ChoiceField(widget=forms.RadioSelect, choices=BOOL_CHOICES, required=True, initial=True,
                                     label=u"请求类型")
    result_code = forms.ChoiceField(widget=forms.RadioSelect, choices=BOOL_RESULT, required=True, initial=True,
                                    help_text=u'中选择retCode则需要接口返回json数据',
                                    label=u"监控项")

    mail_status = forms.ChoiceField(widget=forms.RadioSelect, choices=BOOL_STATUS, required=True, initial=True,
                                    label=u"邮件报警")
    status = forms.ChoiceField(widget=forms.RadioSelect, choices=BOOL_STATUS, required=True, initial=True,
                               label=u"是否启用")
    weixin_status = forms.ChoiceField(widget=forms.RadioSelect, choices=BOOL_STATUS, required=True, initial=True,
                                      help_text=u'微信报警需先加入团队号',
                                      label=u"微信报警")

    class Meta:
        model = MonitorHttp
        fields = [
            "title",
            "url",
            "monitor_type",
            "monitor_ip",
            "result_code",
            "mail_status",
            "mail",
            "weixin_status",
            "weixin",
            "payload",
            "status",
        ]


class MonitorLogForm(forms.ModelForm):
    class Meta:
        model = MonitorHttpLog
        fields = [
            "monitorId",
            "monitor_title",
            "content",
            "code",
            "job_id"
        ]

monitor/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: views.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午3:43
     History:   
"""

from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from models import MonitorHttp, MonitorHttpLog
from monitor.forms import MonitorHttpForm
import json
import ast


@login_required
def HttpMonitor(request):
    """ 添加http监控 """
    if request.method == 'POST':
        uf = MonitorHttpForm(request.POST)
        if uf.is_valid():
            uf.save()
    else:
        uf = MonitorHttpForm()
    return render_to_response('monitor/httpadd.html', locals(), context_instance=RequestContext(request))


@login_required
def HttpMonitorlist(request):
    """ http监控列表 """
    data = MonitorHttp.objects.all().order_by("-createtime")
    return render_to_response('monitor/httplist.html', locals(), context_instance=RequestContext(request))


@login_required
def HttpMonitorEdit(request, uuid):
    """ http监控列表 """
    data = MonitorHttp.objects.get(pk=uuid)
    if request.method == 'POST':
        uf = MonitorHttpForm(request.POST, instance=data)
        if uf.is_valid():
            uf.save()
    uf = MonitorHttpForm(instance=data)
    return render_to_response('monitor/httpedit.html', locals(), context_instance=RequestContext(request))


@login_required
def HttpMonitorstatus(request, uuid):
    """ http监控列表 """
    data = MonitorHttp.objects.get(pk=uuid)
    data.status = int(request.GET.get("status"))
    data.save()
    return HttpResponse(json.dumps({"retCode": 200, "retMsg": "ok"}, ensure_ascii=False, indent=4))


@login_required
def HttpMonitorDel(request, uuid):
    """ http监控列表 """
    data = MonitorHttp.objects.get(pk=uuid).delete()
    return HttpResponse(json.dumps({"retCode": 200, "retMsg": "ok"}, ensure_ascii=False, indent=4))


@login_required
def HttpMonitorPage(request, uuid):
    """ http监控列表 """
    data = MonitorHttp.objects.get(pk=uuid)
    log_data = MonitorHttpLog.objects.filter(monitorId=uuid).order_by("-createtime")
    return render_to_response('monitor/httppage.html', locals(), context_instance=RequestContext(request))


def HttpMonitorApi(request):
    """ http监控列表 """
    data = MonitorHttp.objects.filter(status=True)
    result = {}
    for i in data:
        if not i.monitor_type:
            result[str(i.pk)] = {"uuid": str(i.uuid), "title": i.title, "url": i.url.split(),
                                 "monitor_type": i.monitor_type,
                                 "ip": i.monitor_ip.split(),
                                 "payload": ast.literal_eval(i.payload),
                                 "mail_status": i.mail_status, "mail": i.mail.split(),
                                 "weixin_status": i.weixin_status, "weixin": "|".join(i.weixin.split()),
                                 "result_code": i.result_code}
        else:
            result[str(i.pk)] = {"uuid": str(i.uuid), "title": i.title, "url": i.url.split(),
                                 "monitor_type": i.monitor_type,
                                 "ip": i.monitor_ip.split(),
                                 "mail_status": i.mail_status, "mail": i.mail.split(),
                                 "weixin_status": i.weixin_status, "weixin": "|".join(i.weixin.split()),
                                 "result_code": i.result_code}


    return HttpResponse(json.dumps({"retCode": 200, "retData": result, "retMsg": "ok"}), content_type = "application/json")

templates/monitor/httpadd.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block content %}
<style>
.PostData{display: none;}
</style>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加http监控 | Add http monitor.</h2>
        </div>
        <div class="col-lg-2">
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <form class="form-horizontal" action="" method="post" name="horizontal" role="form" autocomplete="off">
                    {% csrf_token %}
                    {{ uf.title|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.url|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.monitor_type|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.monitor_ip|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.result_code|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.mail_status|bootstrap_horizontal }}
                    {{ uf.mail|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.weixin_status|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.weixin|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {#                {{ uf.payload|bootstrap_horizontal }}#}

                    <div class="form-group PostData">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_payload">Post数据</label>
                        <div class=" col-sm-10 col-lg-10 ">
                            <textarea class=" form-control" cols="40" id="id_payload" name="payload" rows="5"></textarea>
                            <p class="help-block">
                                POST提交数据,需json格式
                            </p>
                        </div>
                    </div>
                    {{ uf.status|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-5">
                            <button class="btn btn-white" type="submit"> 重置</button>
                            <button class="btn btn-primary" type="submit"> 提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>

<script>
$('#id_monitor_type_0').unbind('click').bind('click', function () {
    $('.PostData').hide();
});
$('#id_monitor_type_1').unbind('click').bind('click', function () {
    $('.PostData').show();
});
</script>
{% endblock content %}



templates/monitor/httpedit.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block content %}
{% if data.monitor_type  %}
<style>
.PostData{display: none;}
</style>
{% endif %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加http监控 | Add http monitor.</h2>
        </div>
        <div class="col-lg-2">
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <form class="form-horizontal" action="" method="post" name="horizontal" role="form" autocomplete="off">
                    {% csrf_token %}
                    {{ uf.title|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.url|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.monitor_type|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.monitor_ip|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.result_code|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.mail_status|bootstrap_horizontal }}
                    {{ uf.mail|bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ uf.weixin_status|bootstrap_horizontal }}
                    {{ uf.weixin|bootstrap_horizontal }}

                    <div class="form-group PostData">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_payload">Post数据</label>
                        <div class=" col-sm-10 col-lg-10 ">
                            <textarea class=" form-control" cols="40" id="id_payload" name="payload" rows="5">{{ data.payload }}</textarea>
                            <p class="help-block">
                                POST提交数据,需json格式
                            </p>
                        </div>
                    </div>
                    {{ uf.status|bootstrap_horizontal }}
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-5">
                            <button class="btn btn-white" type="submit"> 重置</button>
                            <button class="btn btn-primary" type="submit"> 提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>

<script>
$('#id_monitor_type_0').unbind('click').bind('click', function () {
    $('.PostData').hide();
});
$('#id_monitor_type_1').unbind('click').bind('click', function () {
    $('.PostData').show();
});
</script>
{% endblock content %}



templates/monitor/httplist.html
{% extends 'assets/base.html' %}
{% block content %}
{% load pagination_tags %}
{% autopaginate data 30 %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>HTTP 监控列表 | List http monitor.</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5> 监控列表 </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user"></ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">监控名称</th>
                            <th class="text-center">url</th>
                            <th class="text-center">类型</th>
                            <th class="text-center">邮件联系人</th>
                            <th class="text-center">微信联系人</th>
                            <th class="text-center">状态</th>
                            <th class="text-center">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data %}
                            <tr id="{{ i.uuid }}">
                                <td class="text-center"><a href="{% url 'HttpMonitorPage' i.uuid %}"> {{ i.title }}</a></td>
                                <td class="text-left" width="100">
                                    <p>{{ i.url  | linebreaksbr | truncatechars:120}}</p>
                                </td>
                                <td class="text-center">{% if i.monitor_type %} GET {% else %} POST {% endif %}</td>
                                <td class="text-center">{{ i.mail | truncatechars:50 }}</td>
                                <td class="text-center">{{ i.weixin | truncatechars:50}}</td>
                                <td class="text-center">
                                    {% if i.status %}
                                    <a href="{% url 'HttpMonitorstatus' i.uuid %}?status=0" class="btn btn-xs btn-info monitor_status " data-toggle="modal">正常</a>
                                    {% else %}
                                    <a href="{% url 'HttpMonitorstatus' i.uuid %}?status=1" class="btn btn-xs btn-success monitor_status" data-toggle="modal">禁用</a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    <div class="btn-group" data-toggle="buttons">
                                      <a href="{% url 'HttpMonitorEdit' i.uuid %}" class="btn btn-xs btn-warning " data-toggle="modal">日志</a>
                                      <a href="{% url 'HttpMonitorEdit' i.uuid %}" class="btn btn-xs btn-success " data-toggle="modal">修改</a>
                                      <a href="{% url 'HttpMonitorDel' i.uuid %}" uuid="{{ i.uuid }}" class="btn btn-xs btn-danger delete_monitor" data-toggle="modal" onclick="return false">删除</a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% paginate %}
            </div>
        </div>
    </div>
</div>
<script>
    $('.monitor_status').unbind('click').bind('click',function(){
         $.ajax({
             type: "GET",
             url: $(this).attr("href"),                  // 提交的页面
             success: function(msg){
                 window.location.reload();
             }
         });
      });
    $('.delete_monitor').unbind('click').bind('click', function () {
        var uuid = $(this).attr("uuid");
        $.ajax({
             type: "GET",
             url: $(this).attr("href"),                  // 提交的页面
             uuid: $(this).attr("uuid"),
             success: function(msg){

             }
         });
        $("#" + uuid).remove();
        return false;
    });
</script>
{% endblock content %}






templates/monitor/httppage.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> {{ data.title }} 监控 详情 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user"></ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="mail-box-header">
                        <div class="pull-right tooltip-demo">
                            <a href="{% url 'HttpMonitorEdit' data.uuid %}" class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="Reply"><i class="fa fa-reply"></i> 修改</a>
{#                            <a href="mailbox.html" class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="Move to trash"><i class="fa fa-trash-o"></i> </a>#}
                        </div>
                        <h2>
                            {{ data.title }}
                        </h2>
                        <div class="mail-tools tooltip-demo m-t-md">

                            <h3>监控状态: {% if data.status %}监控中{% else %}停止监控{% endif %}</h3>
                            <h5>
                                <span class="font-noraml">微信联系人: </span>{{ data.weixin }}
                            </h5>
                            <h5><span class="font-noraml">From: </span>{{ data.mail }}</h5>
                            <h5><span class="font-noraml">请求方式: </span>{% if data.monitor_type %}GET{% else %}POST{% endif %}</h5>
                            {% if not data.monitor_type %}
                            <h5><span class="font-noraml">提交数据: </span>  </h5>
                            <pre>{{ data.payload }}</pre>
                            {% endif %}
                        </div>
                    </div>
                    <div class="mail-box">
                        <div class="mail-body">
                            <p>
                            {{ data.url | linebreaksbr }}
                            </p>
                            {% for i in log_data %}
                            <p>状态: {{ i.code }}</p>
                            <p>返回信息: {{ i.content }}</p>
                            {% if i.status %}
                            <p>报警状态: 已报警</p>
                            {% endif %}
                            <p>{{ i.createtime }}</p><br>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row wrapper border-bottom white-bg page-heading">

    </div>

{% endblock content %}

