DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

api/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: urls.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午11:15
     History:   
"""

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       # 资产管理
                       url(r'^project/$', 'assets.api.api.type_list'),
                       url(r'^project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),
                       url(r'^user/.*$', 'assets.api.api.user_select'),

                       # 装机操作
                       url(r'^sn/.*$', 'assets.api.api.Sn_number'),
                       url(r'^cmdb/.*$', 'assets.api.api.CmdbUpdate'),

                       # nagios监控接口

                       url(r'^audit/list/.*$', 'audit.views.audit_list'),

                       url(r'^audit/$', 'audit.views.audit_save'),
                       # url(r'^create', 'assets.api.api.saltstack_create_config'),

                       # 安装完成上报接口
                       url(r'^system_install/$', 'assets.value_class.index.install_ok'),
                       url(r'^alert/$', 'malfunction.views.FaultApi'),
                       url(r'^monitor/http', 'monitor.views.HttpMonitorApi'),
                       url(r'^monitor/log', 'api.monitor_api.HttpMonitorLog'),
                       url(r'^xls/', 'api.cmdb_excel.xls_select'),
                       url(r'^cdn/', 'api.cmdb_excel.xls_cdn'),

                       )

malfunction/urls.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-
#=============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 
#      History:
#=============================================================================

from django.conf.urls import patterns, include, url
from assets import views, service_views, salt_cdn_cmdb

urlpatterns = patterns('',

    url(r'^add/$', "malfunction.views.FaultAdd"),
    url(r'^my/$', "malfunction.views.FaultMy"),
    url(r'^nodone/$', "malfunction.views.FaultNoDone", name="FaultNoDone"),
    url(r'^done/$', "malfunction.views.FaultDone"),
    url(r'^source/$', "malfunction.views.FaultSource"),
    url(r'^classical/$', "malfunction.views.FaultClassical"),
    url(r'^edit/(?P<uuid>[^/]+)/$', "malfunction.views.FaultEdit"),
    url(r'^(?P<uuid>[^/]+)/$', "malfunction.views.FaultDetail"),
    url(r'$', "malfunction.views.FaultIndex"),
)



mysite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 2013-02-20 14:52:11
#      History:
# =============================================================================

from django.conf.urls import patterns, include, url
from mysite.settings import MEDIA_ROOT
from django.contrib import admin
from settings import BASE_DIR

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "%s/upload" % BASE_DIR}),

                       url(r'accounts/', include("accounts.urls")),
                       # url(r'^$', 'salt_ui.auto.auto_index_class.auto_index'),
                       url(r'^$', 'salt_ui.views.index.salt_index_new'),
                       url(r'^login/$', 'salt_ui.views.index.auth_login'),
                       url(r'^test/$', 'salt_ui.views.index.test'),
                       # 日志
                       url(r'^logs/salt/', 'salt_ui.views.api_log_class.salt_data_log'),
                       url(r'^logs/host/', "audit.views.audit_list"),

                       # 搜索
                       # url(r'^search/$', 'assets.views.search'),
                       # salt_ui
                       url(r'salt/', include("salt_ui.urls")),
                       # 资产管理
                       url(r'assets/', include("assets.urls")),
                       # url(r'',include(salt_ui.urls)),
                       # 运维自动化
                       url(r'auto/', include("salt_ui.auto.urls")),
                       # 资产api
                       url(r'api/', include("api.urls")),
                       url(r'conf/', include("config.urls")),

                       # 审计模块
                       url(r'^audit/', include("audit.urls")),

                       # admin
                       url(r'^admin/', include(admin.site.urls)),

                       # swan发布接口
                       url(r'swan/', include("swan.urls")),

                       # 故障管理
                       url(r'^incident/', include("malfunction.urls")),

                       # 监控
                       url(r'^monitor/', include("monitor.urls")),

                       # message
                       url(r'^message/', include("message.urls")),

                       # 权限组
                       url(r'^auth/', include("cmdb_auth.urls")),

                       url(r'^ops/doc/$', 'salt_ui.views.index.OpsDoc'),
                       url(r'^api/project/$', 'assets.api.api.type_list'),
                       url(r'^api/project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),

                       url(r'^ueditor/', include('DjangoUeditor.urls')),


                       # url(r'^summernote/', include('django_summernote.urls')),
                       #
                       )

malfunction/models.py
#!/usr/bin/env python
#   -*- coding: utf-8 -*-
#   =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#      History:
#   =============================================================================

from django.db import models
from uuidfield import UUIDField
from DjangoUeditor.models import UEditorField

malf_status = (
    (0, u"处理中"),
    (1, u"未处理"),
    (2, u"关闭"),
)

source_data = (
    (0, u"zabbix"),
    (1, u"nagios"),
    (2, u"cacti"),
    (3, u"smokeping"),
    (4, u"监控脚本"),
    (5, u"监控宝"),
    (6, u"其它"),
)

grade_data = (
    (0, u"高危"),
    (1, u"严重"),
    (2, u"中级"),
    (3, u"一般"),
    (4, u"无影响"),
)


class Incident(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    title = models.CharField(max_length=256, verbose_name=u'标题')
    ip = models.IPAddressField(blank=True, null=True, verbose_name=u'ip')
    url = models.TextField(blank=True, null=True, verbose_name=u'URL')
    projectuser = models.CharField(max_length=32, verbose_name=u'业务负责人',
                                   help_text=u'业务维护人员,输入中文名称')
    closeuser = models.CharField(max_length=32, blank=True, null=True, verbose_name=u'故障处理人员')
    # type = models.IntegerField(verbose_name=u"机房类型", choices=source_data, max_length=32, blank=True, null=True)
    source = models.IntegerField(choices=source_data, max_length=4, verbose_name=u'报障来源')
    starttime = models.DateTimeField(verbose_name=u'发生时间')
    scantime = models.DateTimeField(verbose_name=u'发现时间', blank=True, null=True, )
    stoptime = models.DateTimeField(blank=True, null=True, verbose_name=u'结束时间')
    # mailcomment = models.TextField(blank=True, null=True, verbose_name=u'报警内容')
    mailcomment = UEditorField(u'报警内容', width=800, height=300, filePath="", upload_settings={"imageMaxSize": 1204000},
                           settings={}, command=None, blank=True)
    # status = models.BooleanField(default=0, verbose_name=u'关闭')
    status = models.IntegerField(verbose_name=u"处理状态", choices=malf_status, max_length=32, default=1)
    classical = models.BooleanField(default=0, verbose_name=u'设为案例')
    grade = models.IntegerField(verbose_name=u'故障等级', max_length=64, blank=True, null=True, choices=grade_data)
    # comment = models.TextField(blank=True, null=True, verbose_name=u'处理过程')
    comment = UEditorField(u'处理过程', width=800, height=300, filePath="", upload_settings={"imageMaxSize": 1204000},
                           settings={}, command=None, blank=True, default="")
    project_principal = models.CharField(verbose_name=u'项目负责人', max_length=32, null=True, blank=True, default="",
                                         help_text=u"如需要邮件通知项目负责人,请填写项目负责人邮箱")
    incident_user = models.CharField(max_length=32, blank=True, null=True)
    createtime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        managed = True
        db_table = 'incident'
        verbose_name = u"故障管理"
        verbose_name_plural = verbose_name

templates/malfunction/add.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block head %}
{{ data.media }}
{% endblock %}
{% block content %}
    <style>
    .checkbox label{margin-right:18px;}
    </style>
         <div class="wrapper wrapper-content">
            <div class="row">
            {% include 'malfunction/left.html' %}
            <div class="col-lg-9 animated fadeInRight">
            <div class="mail-box-header">

                <h2>
                    Incident add
                </h2>
            </div>
                <form class="form-horizontal" id="form_data" method="POST" action="">{% csrf_token %}
                <div class="mail-box">
                <div class="mail-body">
                        {{ data.title | bootstrap_horizontal }}
                        {{ data.source | bootstrap_horizontal }}
                        <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_title">URL:</label>
                            <div class=" col-sm-8 col-lg-8 ">
                                <input class=" form-control" id="id_url" maxlength="256" name="url" type="text" />
                            </div>
                        </div>
                        {{ data.grade | bootstrap_horizontal }}
                        {{ data.mailcomment | bootstrap_horizontal }}
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_title">发生时间:</label>
                            <div class=" col-sm-8 col-lg-8 ">
                                <input class=" form-control" id="id_starttime" maxlength="256" name="starttime" value="{{ date_time }}" type="text" />
                            </div>
                        </div>
                        <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_title">发现时间:</label>
                            <div class=" col-sm-8 col-lg-8 ">
                                <input class=" form-control" id="id_scantime" maxlength="256" name="scantime" value="{{ date_time }}" type="text" />
                            </div>
                        </div>
                        <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_title">结束时间:</label>
                            <div class=" col-sm-8 col-lg-8 ">
                                <input class=" form-control" id="id_stoptime" maxlength="256" name="stoptime"  type="text" />
                            </div>
                        </div>
                        {{ data.projectuser | bootstrap_horizontal }}
                        {{ data.project_status | bootstrap_horizontal }}
{#                        {{ data.project_principal | bootstrap_horizontal }}#}
                        <div class="form-group voilet_form_status">
                            <label class="control-label col-sm-2 col-lg-2 " for="id_project_principal">项目负责人</label>
                            <div class=" col-sm-10 col-lg-10 ">
                                <input class=" form-control" id="id_project_principal" maxlength="32" name="project_principal" type="text" />
                                    <p class="help-block">
                                        {{ data.project_principal.help_text }}
                                    </p>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
{#                        <div class="form-group">#}
{#                            <label class="control-label col-sm-2 col-lg-2 " for="id_mailcomment">处理过程</label>#}
{#                            <div class=" col-sm-8 col-lg-8 ">#}
{#                                <div class="mail-text h-200">#}
{#                                {{ data.comment }}#}
{#                                <div class="clearfix"></div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
                    {{ data.comment |bootstrap_horizontal }}
                    <div class="hr-line-dashed"></div>
                    {{ data.status |bootstrap_horizontal }}


                    <div class="clearfix"></div>
                        <div class="form-group">
                                <div class=" col-sm-offset-2 col-sm-8 col-lg-offset-2 col-lg-8">
                                    <div class="checkbox">
                                        <label >
                                            <input  id="id_classical" class="checkbox-line" name="classical" type="checkbox"  /> <span>设为案例</span>
                                        </label>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                        </div>
                    <div class="clearfix"></div>

                </div>


                    <div class="form-group">
                       <div class="col-sm-4 col-sm-offset-5">
                           <button class="btn btn-white" type="submit"> 重置 </button>
                           <button class="btn btn-primary" type="submit"> 提交 </button>
                       </div>
                   </div>

                </div>
                </form>
            </div>
        </div>
     </div>
<script>
$('#id_project_status_1').unbind('click').bind('click', function () {
    $('.voilet_form_status').hide();
});
$('#id_project_status_0').unbind('click').bind('click', function () {
    $('.voilet_form_status').show();
});
</script>
{% endblock %}

templates/malfunction/add1.html
{% extends 'default/base.html' %}
<style>
.voilet{margin-top:120px;}
.wrapper-content{background-color: #ffffff;}
</style>
{% block content %}

         <div class="wrapper wrapper-content">
            <div class="row">
            {% include "malfunction/left.html" %}
            <div class="col-lg-9 animated fadeInRight">
                <div class="mail-box-header">
                    <div class="pull-right tooltip-demo">
                        <a href="mailbox.html" class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="Move to draft folder"><i class="fa fa-pencil"></i> Draft</a>
                        <a href="mailbox.html" class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Discard email"><i class="fa fa-times"></i> Discard</a>
                    </div>
                    <h2>
                        Compse mail
                    </h2>
                </div>
                <form class="form-horizontal" id="form_data"  method="post" role="form" >{% csrf_token %}
                    <div class="hero-unit">
                        <div id="alerts"></div>
                        <div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
                          <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="icon-font"></i><b class="caret"></b></a>
                              <ul class="dropdown-menu">
                              </ul>
                            </div>
                          <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="icon-text-height"></i>&nbsp;<b class="caret"></b></a>
                              <ul class="dropdown-menu">
                              <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
                              <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
                              <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
                              </ul>
                          </div>
                          <div class="btn-group">
                            <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
                            <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
                            <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
                            <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
                          </div>
                          <div class="btn-group">
                            <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
                            <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
                            <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
                            <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
                          </div>
                          <div class="btn-group">
                            <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
                            <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
                            <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
                            <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
                          </div>
                          <div class="btn-group">
                              <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="icon-link"></i></a>
                                <div class="dropdown-menu input-append">
                                    <input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
                                    <button class="btn" type="button">Add</button>
                            </div>
                            <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="icon-cut"></i></a>

                          </div>

                          <div class="btn-group">
                            <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="icon-picture"></i></a>
                            <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
                          </div>
                          <div class="btn-group">
                            <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
                            <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
                          </div>
                          <input type="text" data-edit="inserttext" id="voiceBtn" x-webkit-speech="">
                        </div>

                        <div id="editor" name="comment">
                          asdfasdfsaf
                        </div>
                      </div>
                    <div class="mail-body text-right tooltip-demo">
                        <div class="form-group">
                           <div class="col-sm-4 col-sm-offset-5">
                               <button class="btn btn-white" type="submit"> 重置 </button>
                               <a class="btn btn-primary click_post" > 提交 </a>
                           </div>
                       </div>

                    </div>
                </form>
            </div>
        </div>
     </div>
<script>
  $(function(){
    function initToolbarBootstrapBindings() {
      var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier',
            'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
            'Times New Roman', 'Verdana'],
            fontTarget = $('[title=Font]').siblings('.dropdown-menu');
      $.each(fonts, function (idx, fontName) {
          fontTarget.append($('<li><a data-edit="fontName ' + fontName +'" style="font-family:\''+ fontName +'\'">'+fontName + '</a></li>'));
      });
      $('a[title]').tooltip({container:'body'});
    	$('.dropdown-menu input').click(function() {return false;})
		    .change(function () {$(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle');})
        .keydown('esc', function () {this.value='';$(this).change();});

      $('[data-role=magic-overlay]').each(function () {
        var overlay = $(this), target = $(overlay.data('target'));
        overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
      });
      if ("onwebkitspeechchange"  in document.createElement("input")) {
        var editorOffset = $('#editor').offset();
        $('#voiceBtn').css('position','absolute').offset({top: editorOffset.top, left: editorOffset.left+$('#editor').innerWidth()-35});
      } else {
        $('#voiceBtn').hide();
      }
	};
	function showErrorAlert (reason, detail) {
		var msg='';
		if (reason==='unsupported-file-type') { msg = "Unsupported format " +detail; }
		else {
			console.log("error uploading file", reason, detail);
		}
		$('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>'+
		 '<strong>File upload error</strong> '+msg+' </div>').prependTo('#alerts');
	};
    initToolbarBootstrapBindings();
	$('#editor').wysiwyg({ fileUploadError: showErrorAlert} );
    window.prettyPrint && prettyPrint();
  });

    $('.click_post').unbind('click').bind('click',function(){
            console.log("aaa");
        $.ajax({

             type: "POST",
             url: $(this).attr("href"),                  // 提交的页面
             data: $('#form_data').serialize(), // 从表单中获取数据
             dataType:'text',
             success: function(msg){
                 $("#result").html(msg);
             }
         });
        return false;
     });
</script>

{% endblock %}

templates/malfunction/detail.html
{% extends 'default/base.html' %}

{% block content %}
    <style>
    .mail-date{width:200px;}
    .mail-ontact{width:100px;}
    </style>
         <div class="wrapper wrapper-content">
            <div class="row">
            {% include 'malfunction/left.html' %}
            <div class="col-lg-9 animated fadeInRight">
            <div class="mail-box-header">
                <div class="pull-right tooltip-demo">
                    <a href="/incident/edit/{{ data.uuid }}/" class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="解决"><i class="fa fa-reply"></i> 解决</a>

                </div>
                <h2>
                    故障详情
                </h2>
                <div class="mail-tools tooltip-demo m-t-md">
                    <h3>
                        <span class="font-noraml"></span>{{ data.title }}
                    </h3>
                    <h4><span class="font-noraml">故障等级: {{ data.get_grade_display }}</span></h4>
                    <h5>
                        <span class="pull-right font-noraml">解决时间: {{ data.stoptime | safe }}</span>
                        <span class="font-noraml">业务负责人: {% if data.projectuser %}{{ data.projectuser }}{% endif %}</span>
                    </h5>
                </div>
            </div>
            <div class="mail-box">
            <div class="mail-body">
                <p>
{#                    报障来源: {% for i in source %} {% if data.get_source_display() %} {{ data.source }}#}
                    报障来源: {{ data.source }}
                    </p>
                    发生时间: {{ data.starttime }}
                    </p>
                    发现时间: {% if data.scantime %}{{ data.scantime }}{% endif %}
                    </p>
                    <p>解决时间: {{ data.stoptime }}</p>
                    故障时长: {{ sum_time }}
                    </p>
                    {% if data.closeuser %}
                    故障处理人员: {{ data.closeuser }}
                    </p>
                    {% endif %}
                    {% if data.url %}
                    URL: <a href="{{ data.url }}" target="_blank">{{ data.url }}</a>
                    {% endif %}

                <br/>

                <p>
                    <h3>报障内容</h3>
                    {{ data.mailcomment|safe}}
                    </p>
                <br/>
                <p>
                    <h3>处理过程</h3>
                    <br/>
                    {% if data.comment  %}
                    {{ data.comment|safe }}
                    {% endif %}
                    </p>
                </p>
            </div>
        </div>
     </div>


{% endblock %}

templates/malfunction/edit.html
{% extends 'default/base.html' %}
{% load bootstrap %}

{% block content %}
    {{ data.media }}
         <div class="wrapper wrapper-content">
            <div class="row">
            {% include 'malfunction/left.html' %}
            <div class="col-lg-9 animated fadeInRight">
            <div class="mail-box-header">

                <h2>
                    Incident add
                </h2>
            </div>
                <form class="form-horizontal" method="POST" action="">{% csrf_token %}
                <div class="mail-box">
                <div class="mail-body">
                        {{ data.title | bootstrap_horizontal }}
                        {{ data.source | bootstrap_horizontal }}
                        <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2 " for="id_title">URL:</label>
                            <div class=" col-sm-8 col-lg-8 ">
                                <input class=" form-control" id="id_url" maxlength="256" name="url" value="{{ faul_data.url }}" type="text" />
                            </div>
                        </div>
{#                        {{ data.url | bootstrap_horizontal }}#}
                        {{ data.grade | bootstrap_horizontal }}
                        {% if faul_data.source == "smokeping" %}
                            <div hidden="hidden">{{ data.mailcomment | bootstrap_horizontal }}</div>
                        {% else %}
                            {{ data.mailcomment | bootstrap_horizontal }}
                        {% endif %}
                        {{ data.starttime | bootstrap_horizontal }}
                        {{ data.scantime | bootstrap_horizontal }}
                        {{ data.stoptime | bootstrap_horizontal }}
                        {{ data.projectuser | bootstrap_horizontal }}
                        {{ data.project_principal | bootstrap_horizontal }}
{#                        <div class="form-group">#}
{#                            <label class="control-label col-sm-2 col-lg-2 " for="id_mailcomment">处理过程</label>#}
{#                            <div class=" col-sm-8 col-lg-8 ">#}
{#                                <div class="mail-text h-200">#}
{#                                {{ data.comment }}#}
{#                                <div class="clearfix"></div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
                        <div class="hr-line-dashed"></div>
                        {{ data.comment | bootstrap_horizontal }}
                        <div class="hr-line-dashed"></div>
                        {{ data.status | bootstrap_horizontal }}
                        <div class="form-group">
                                <div class=" col-sm-offset-2 col-sm-8 col-lg-offset-2 col-lg-8">
                                    <div class="checkbox">
{#                                            <label >#}
{#                                                {% if status %}#}
{#                                                <input id="id_status" class="checkbox-line" checked name="status" type="checkbox"  /> <span>关闭</span>#}
{#                                                {% else %}#}
{#                                                <input id="id_status" class="checkbox-line" name="status" type="checkbox"  /> <span>关闭</span>#}
{#                                                {% endif %}#}
{#                                            </label>#}
                                            <label >
                                                {% if classical %}
                                                <input  id="id_classical" class="checkbox-line" checked name="classical" type="checkbox"  /> <span>设为案例</span>
                                                {% else %}
                                                <input  id="id_classical" class="checkbox-line" name="classical" type="checkbox"  /> <span>设为案例</span>
                                                {% endif %}
                                            </label>
                                    </div>
                                </div>
                        </div>


                </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                       <div class="col-sm-4 col-sm-offset-5">
                           <button class="btn btn-white" type="submit"> 重置 </button>
                           <button class="btn btn-primary" type="submit"> 提交 </button>
                       </div>
                   </div>


                </div>
                </form>
            </div>
        </div>
     </div>

    <script>
        $(document).ready(function(){
            $('.summernote').summernote({
                height: 180
            });
        });
    </script>

{% endblock %}